name: "Versioning Branch Semantic"
description: "Calculate the next version from branch name and rules in TOML config"

inputs:
  branch:
    description: "Branch name"
    required: true
  prerelease:
    description: "Whether it's a prerelease (true/false)"
    required: false
    default: "false"
  config-file:
    description: "Path to config TOML file (default: pyproject.toml)"
    required: false
    default: "pyproject.toml"

outputs:
  version:
    value: ${{ steps.calc.outputs.version }}
    description: "Calculated version string"
  deploy:
    value: ${{ steps.calc.outputs.deploy }}
    description: "Whether this branch should trigger a deploy (true/false)"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: ./actions/python/uv-requirements
      with:
        requirements: ${{ github.action_path }}/requirements.txt

    - name: Calculate version
      id: calc
      shell: bash
      run: |
        result=$(uv run python ${{ github.action_path }}/src/cli.py \
          --branch "${{ inputs.branch }}" \
          --prerelease "${{ inputs.prerelease }}" \
          --config "${{ inputs.config-file }}")
        version=$(echo "$result" | grep '^version=' | cut -d= -f2)
        deploy=$(echo "$result" | grep '^deploy=' | cut -d= -f2)
        echo "Calculated result: $result"
        echo "Calculated version: $version"
        echo "Calculated deploy: $deploy"
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "deploy=$deploy" >> $GITHUB_OUTPUT
